// VENDORED, PINNED COPY (Symoto Phase 3, MODEL-02). Do not edit by hand.
// This is a verbatim copy of the bespoke Orchid City engine's coefficient set,
// frozen so the Symoto OC model computes from the identical numbers the golden
// master was captured from, with no cross-repo runtime dependency.
//
// Provenance:
//   source xlsx:          data/spreadsheets/dev-model.xlsx (vizapp)
//   coefficients commit:  d3c93d129fc595c50ba794a4b790c1be025ca471 (vizapp src/sim/coefficients.generated.ts)
//   vizapp HEAD at copy:  fc732f5a2eb9be35fff1d014d6267c706b521351
//   baselinePopulation:   50000
//   countries:            Netherlands, Vietnam, Brazil
//
// AUTO-GENERATED by scripts/extract_model.py — do not edit by hand (lineage note).
// Source of truth: data/spreadsheets/dev-model.xlsx
import type { ModelCoefficients } from './config.js';

export const COEFFICIENTS: ModelCoefficients = {
  "meta": {
    "source": "data/spreadsheets/dev-model.xlsx",
    "baselinePopulation": 50000.0,
    "countries": [
      "Netherlands",
      "Vietnam",
      "Brazil"
    ]
  },
  "programs": [
    {
      "category": "Housing",
      "name": "Medium Villa",
      "code": "H-001",
      "units": {
        "Netherlands": 3523.88,
        "Vietnam": 2814.301153,
        "Brazil": 2799.496101
      },
      "gfaPerUnit": {
        "Netherlands": 189.0,
        "Vietnam": 350.0,
        "Brazil": 189.0
      },
      "footprintPerUnit": {
        "Netherlands": 94.5,
        "Vietnam": 175.0,
        "Brazil": 77.5
      },
      "gardenPerUnit": {
        "Netherlands": 100.0,
        "Vietnam": 100.0,
        "Brazil": 100.0
      },
      "terracePerUnit": {
        "Netherlands": 12.0,
        "Vietnam": 12.0,
        "Brazil": 12.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1750.0,
        "Vietnam": 875,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 2986,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Large Villa",
      "code": "H-002",
      "units": {
        "Netherlands": 500,
        "Vietnam": 337.7161383,
        "Brazil": 349.9370126
      },
      "gfaPerUnit": {
        "Netherlands": 211.0,
        "Vietnam": 420.0,
        "Brazil": 211.0
      },
      "footprintPerUnit": {
        "Netherlands": 105.5,
        "Vietnam": 210.0,
        "Brazil": 102.5
      },
      "gardenPerUnit": {
        "Netherlands": 150.0,
        "Vietnam": 150.0,
        "Brazil": 150.0
      },
      "terracePerUnit": {
        "Netherlands": 20.0,
        "Vietnam": 20.0,
        "Brazil": 20.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 2000.0,
        "Vietnam": 1000,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 2986,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Semi-detached",
      "code": "H-003",
      "units": {
        "Netherlands": 4976.29,
        "Vietnam": 3242.074928,
        "Brazil": 3149.433113
      },
      "gfaPerUnit": {
        "Netherlands": 161.0,
        "Vietnam": 200.0,
        "Brazil": 161.0
      },
      "footprintPerUnit": {
        "Netherlands": 53.66666667,
        "Vietnam": 100.0,
        "Brazil": 77.5
      },
      "gardenPerUnit": {
        "Netherlands": 60.0,
        "Vietnam": 60.0,
        "Brazil": 60.0
      },
      "terracePerUnit": {
        "Netherlands": 8.0,
        "Vietnam": 8.0,
        "Brazil": 8.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1500.0,
        "Vietnam": 750,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 2625,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Rowhouse",
      "code": "H-004",
      "units": {
        "Netherlands": 4000,
        "Vietnam": 3287.103746,
        "Brazil": 2000.04
      },
      "gfaPerUnit": {
        "Netherlands": 141.0,
        "Vietnam": 150.0,
        "Brazil": 141.0
      },
      "footprintPerUnit": {
        "Netherlands": 47,
        "Vietnam": 50.0,
        "Brazil": 67.5
      },
      "gardenPerUnit": {
        "Netherlands": 50.0,
        "Vietnam": 50.0,
        "Brazil": 50.0
      },
      "terracePerUnit": {
        "Netherlands": 8.0,
        "Vietnam": 8.0,
        "Brazil": 8.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1750.0,
        "Vietnam": 875,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 2627,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Rowhouse (Social)",
      "code": "H-005",
      "units": {
        "Netherlands": 3000,
        "Vietnam": 2476.585014,
        "Brazil": 2099.622076
      },
      "gfaPerUnit": {
        "Netherlands": 141.0,
        "Vietnam": 150.0,
        "Brazil": 141.0
      },
      "footprintPerUnit": {
        "Netherlands": 47,
        "Vietnam": 50.0,
        "Brazil": 67.5
      },
      "gardenPerUnit": {
        "Netherlands": 50.0,
        "Vietnam": 50.0,
        "Brazil": 50.0
      },
      "terracePerUnit": {
        "Netherlands": 8.0,
        "Vietnam": 8.0,
        "Brazil": 8.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1500.0,
        "Vietnam": 750,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Appt: 2 Bedroom",
      "code": "H-006",
      "units": {
        "Netherlands": 750,
        "Vietnam": 1891.210375,
        "Brazil": 333.34
      },
      "gfaPerUnit": {
        "Netherlands": 110.0,
        "Vietnam": 85.0,
        "Brazil": 110.0
      },
      "footprintPerUnit": {
        "Netherlands": 27.5,
        "Vietnam": 17,
        "Brazil": 67.5
      },
      "gardenPerUnit": {
        "Netherlands": 20.0,
        "Vietnam": 20.0,
        "Brazil": 20.0
      },
      "terracePerUnit": {
        "Netherlands": 4.0,
        "Vietnam": 4.0,
        "Brazil": 4.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1500.0,
        "Vietnam": 750,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 3487,
        "Vietnam": 1500.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Appt: Studio",
      "code": "H-007",
      "units": {
        "Netherlands": 500,
        "Vietnam": 315.2017291,
        "Brazil": 349.9370126
      },
      "gfaPerUnit": {
        "Netherlands": 75.0,
        "Vietnam": 55.0,
        "Brazil": 75.0
      },
      "footprintPerUnit": {
        "Netherlands": 18.75,
        "Vietnam": 13.75,
        "Brazil": 63.0
      },
      "gardenPerUnit": {
        "Netherlands": 20.0,
        "Vietnam": 20.0,
        "Brazil": 20.0
      },
      "terracePerUnit": {
        "Netherlands": 4.0,
        "Vietnam": 4.0,
        "Brazil": 4.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1500.0,
        "Vietnam": 750,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 3487,
        "Vietnam": 1500.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Appt: Seniors",
      "code": "H-008",
      "units": {
        "Netherlands": 2000,
        "Vietnam": 315.2017291,
        "Brazil": 2500.05
      },
      "gfaPerUnit": {
        "Netherlands": 70.0,
        "Vietnam": 50.0,
        "Brazil": 70.0
      },
      "footprintPerUnit": {
        "Netherlands": 17.5,
        "Vietnam": 12.5,
        "Brazil": 17.5
      },
      "gardenPerUnit": {
        "Netherlands": 20.0,
        "Vietnam": 20.0,
        "Brazil": 20.0
      },
      "terracePerUnit": {
        "Netherlands": 4.0,
        "Vietnam": 4.0,
        "Brazil": 4.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1750.0,
        "Vietnam": 875,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 3487,
        "Vietnam": 1500.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Appt: Student Housing",
      "code": "H-009",
      "units": {
        "Netherlands": 500,
        "Vietnam": 315.2017291,
        "Brazil": 349.9370126
      },
      "gfaPerUnit": {
        "Netherlands": 60.0,
        "Vietnam": 50.0,
        "Brazil": 60.0
      },
      "footprintPerUnit": {
        "Netherlands": 15,
        "Vietnam": 12.5,
        "Brazil": 15
      },
      "gardenPerUnit": {
        "Netherlands": 20.0,
        "Vietnam": 20.0,
        "Brazil": 20.0
      },
      "terracePerUnit": {
        "Netherlands": 4.0,
        "Vietnam": 4.0,
        "Brazil": 4.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1500.0,
        "Vietnam": 750,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 740.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Housing",
      "name": "Appt: Social Housing (2bdrm)",
      "code": "H-010",
      "units": {
        "Netherlands": 4060,
        "Vietnam": 630.4034582,
        "Brazil": 2733.388
      },
      "gfaPerUnit": {
        "Netherlands": 80.0,
        "Vietnam": 50.0,
        "Brazil": 80.0
      },
      "footprintPerUnit": {
        "Netherlands": 20,
        "Vietnam": 12.5,
        "Brazil": 20
      },
      "gardenPerUnit": {
        "Netherlands": 20.0,
        "Vietnam": 20.0,
        "Brazil": 20.0
      },
      "terracePerUnit": {
        "Netherlands": 4.0,
        "Vietnam": 4.0,
        "Brazil": 4.0
      },
      "storagePerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1500.0,
        "Vietnam": 750,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 740.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Schools",
      "name": "Daycare",
      "code": null,
      "units": {
        "Netherlands": 23,
        "Vietnam": 32,
        "Brazil": 1
      },
      "gfaPerUnit": {
        "Netherlands": 3.0,
        "Vietnam": 8.0,
        "Brazil": 3.0
      },
      "footprintPerUnit": {
        "Netherlands": 500.0,
        "Vietnam": 500.0,
        "Brazil": 500.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1400.0,
        "Vietnam": 700,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Schools",
      "name": "Primary school",
      "code": null,
      "units": {
        "Netherlands": 24,
        "Vietnam": 26,
        "Brazil": 1
      },
      "gfaPerUnit": {
        "Netherlands": 5.0,
        "Vietnam": 6.0,
        "Brazil": 5.0
      },
      "footprintPerUnit": {
        "Netherlands": 1500.0,
        "Vietnam": 1500.0,
        "Brazil": 1500.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1400.0,
        "Vietnam": 700,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 800.0
    },
    {
      "category": "Schools",
      "name": "High school",
      "code": null,
      "units": {
        "Netherlands": 1,
        "Vietnam": 1,
        "Brazil": 1
      },
      "gfaPerUnit": {
        "Netherlands": 10.0,
        "Vietnam": 6.0,
        "Brazil": 10.0
      },
      "footprintPerUnit": {
        "Netherlands": 4000.0,
        "Vietnam": 3000.0,
        "Brazil": 3000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1400.0,
        "Vietnam": 700,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 5000.0
    },
    {
      "category": "Schools",
      "name": "Craft school*",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 11,
        "Brazil": 1
      },
      "gfaPerUnit": {
        "Netherlands": 10.0,
        "Vietnam": 10.0,
        "Brazil": 10.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1400.0,
        "Vietnam": 700,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 5000.0
    },
    {
      "category": "Hospitality",
      "name": "Hotel",
      "code": null,
      "units": {
        "Netherlands": 17,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 3000.0,
        "Vietnam": 3000.0,
        "Brazil": 3000.0
      },
      "footprintPerUnit": {
        "Netherlands": 750,
        "Vietnam": 750,
        "Brazil": 750
      },
      "gardenPerUnit": {
        "Netherlands": 400.0,
        "Vietnam": 400.0,
        "Brazil": 400.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 2000.0,
        "Vietnam": 1000,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 3300.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 3000.0
    },
    {
      "category": "Hospitality",
      "name": "Resort",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 16,
        "Brazil": 16
      },
      "gfaPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "footprintPerUnit": {
        "Netherlands": 3000.0,
        "Vietnam": 3000.0,
        "Brazil": 3000.0
      },
      "gardenPerUnit": {
        "Netherlands": 30000.0,
        "Vietnam": 30000.0,
        "Brazil": 30000.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 2000.0,
        "Vietnam": 1000,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 4000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 5000.0
    },
    {
      "category": "Hospitality",
      "name": "Restaurant",
      "code": null,
      "units": {
        "Netherlands": 167,
        "Vietnam": 167,
        "Brazil": 167
      },
      "gfaPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "footprintPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "gardenPerUnit": {
        "Netherlands": 200.0,
        "Vietnam": 200.0,
        "Brazil": 200.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 2000.0,
        "Vietnam": 1000,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": 4000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 300.0
    },
    {
      "category": "Retail",
      "name": "Retail",
      "code": null,
      "units": {
        "Netherlands": 25,
        "Vietnam": 69,
        "Brazil": 1
      },
      "gfaPerUnit": {
        "Netherlands": 2000.0,
        "Vietnam": 2000.0,
        "Brazil": 2000.0
      },
      "footprintPerUnit": {
        "Netherlands": 2000.0,
        "Vietnam": 2000.0,
        "Brazil": 2000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 880.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 50.0,
        "Brazil": 0.0
      },
      "minPopulation": 600.0
    },
    {
      "category": "Retail",
      "name": "Cafe store",
      "code": null,
      "units": {
        "Netherlands": 100,
        "Vietnam": 25,
        "Brazil": 25
      },
      "gfaPerUnit": {
        "Netherlands": 60.0,
        "Vietnam": 60.0,
        "Brazil": 60.0
      },
      "footprintPerUnit": {
        "Netherlands": 60,
        "Vietnam": 60,
        "Brazil": 60
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Retail",
      "name": "Convenience Store / Super",
      "code": null,
      "units": {
        "Netherlands": 1,
        "Vietnam": 11.1,
        "Brazil": 11.1
      },
      "gfaPerUnit": {
        "Netherlands": 400.0,
        "Vietnam": 400.0,
        "Brazil": 400.0
      },
      "footprintPerUnit": {
        "Netherlands": 400,
        "Vietnam": 400,
        "Brazil": 400
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 300.0
    },
    {
      "category": "Retail",
      "name": "Market",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 1.0,
        "Brazil": 25
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 2000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 800.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 3000.0
    },
    {
      "category": "Offices",
      "name": "Offices",
      "code": null,
      "units": {
        "Netherlands": 110,
        "Vietnam": 0,
        "Brazil": 0
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1400.0,
        "Vietnam": 915.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 26.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Offices",
      "name": "co-working spaces /  Meeting room",
      "code": null,
      "units": {
        "Netherlands": 138,
        "Vietnam": 0,
        "Brazil": 0
      },
      "gfaPerUnit": {
        "Netherlands": 200.0,
        "Vietnam": 200.0,
        "Brazil": 200.0
      },
      "footprintPerUnit": {
        "Netherlands": 100.0,
        "Vietnam": 100.0,
        "Brazil": 100.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1400.0,
        "Vietnam": null,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 500.0
    },
    {
      "category": "Offices",
      "name": "Conference center",
      "code": null,
      "units": {
        "Netherlands": 1,
        "Vietnam": 1,
        "Brazil": 1
      },
      "gfaPerUnit": {
        "Netherlands": 10000.0,
        "Vietnam": 10000.0,
        "Brazil": 10000.0
      },
      "footprintPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 5000.0
    },
    {
      "category": "Leisure",
      "name": "Central Community center",
      "code": null,
      "units": {
        "Netherlands": 1.0,
        "Vietnam": 1.0,
        "Brazil": 1.0
      },
      "gfaPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "footprintPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Leisure",
      "name": "Satellite community centers",
      "code": null,
      "units": {
        "Netherlands": 50,
        "Vietnam": 50,
        "Brazil": 50
      },
      "gfaPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "footprintPerUnit": {
        "Netherlands": 125.0,
        "Vietnam": 125.0,
        "Brazil": 125.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 800.0
    },
    {
      "category": "Leisure",
      "name": "Central Event Space",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "footprintPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 3000.0
    },
    {
      "category": "Leisure",
      "name": "Music & Culture",
      "code": null,
      "units": {
        "Netherlands": 100,
        "Vietnam": 100,
        "Brazil": 100
      },
      "gfaPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "footprintPerUnit": {
        "Netherlands": 125.0,
        "Vietnam": 125.0,
        "Brazil": 125.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1000.0
    },
    {
      "category": "Leisure",
      "name": "Sports, Covered",
      "code": null,
      "units": {
        "Netherlands": 50,
        "Vietnam": 50,
        "Brazil": 50
      },
      "gfaPerUnit": {
        "Netherlands": 1250.0,
        "Vietnam": 3000.0,
        "Brazil": 1250.0
      },
      "footprintPerUnit": {
        "Netherlands": 10000.0,
        "Vietnam": 10000.0,
        "Brazil": 10000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1000.0
    },
    {
      "category": "Leisure",
      "name": "Art galleries",
      "code": null,
      "units": {
        "Netherlands": 33,
        "Vietnam": 33,
        "Brazil": 33
      },
      "gfaPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "footprintPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 4999.0
    },
    {
      "category": "Leisure",
      "name": "Religious infrastructure*",
      "code": null,
      "units": {
        "Netherlands": 20,
        "Vietnam": 20,
        "Brazil": 20
      },
      "gfaPerUnit": {
        "Netherlands": 5000.0,
        "Vietnam": 5000.0,
        "Brazil": 5000.0
      },
      "footprintPerUnit": {
        "Netherlands": 2000.0,
        "Vietnam": 2000.0,
        "Brazil": 2000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": null
    },
    {
      "category": "Health & Care",
      "name": "Spa",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 5,
        "Brazil": 5
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 500.0,
        "Vietnam": 500.0,
        "Brazil": 500.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 2200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 4999.0
    },
    {
      "category": "Health & Care",
      "name": "Senior care",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 3,
        "Brazil": 5
      },
      "gfaPerUnit": {
        "Netherlands": 600.0,
        "Vietnam": 600.0,
        "Brazil": 600.0
      },
      "footprintPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1600.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 499.0
    },
    {
      "category": "Health & Care",
      "name": "Health Center",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 3,
        "Brazil": 5
      },
      "gfaPerUnit": {
        "Netherlands": 800.0,
        "Vietnam": 500.0,
        "Brazil": 800.0
      },
      "footprintPerUnit": {
        "Netherlands": 400.0,
        "Vietnam": 400.0,
        "Brazil": 400.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1600.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 499.0
    },
    {
      "category": "Services",
      "name": "General Maintenance",
      "code": null,
      "units": {
        "Netherlands": 0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gfaPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "footprintPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Power infrastructure",
      "code": null,
      "units": {
        "Netherlands": 10.0,
        "Vietnam": 10.0,
        "Brazil": 10.0
      },
      "gfaPerUnit": {
        "Netherlands": 150.0,
        "Vietnam": 150.0,
        "Brazil": 150.0
      },
      "footprintPerUnit": {
        "Netherlands": 150.0,
        "Vietnam": 150.0,
        "Brazil": 150.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 120.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Powerplant",
      "code": null,
      "units": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gfaPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "footprintPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 120.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Converter stations and powerlines",
      "code": null,
      "units": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gfaPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "footprintPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 120.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Water infrastructure",
      "code": null,
      "units": {
        "Netherlands": 5,
        "Vietnam": 5.0,
        "Brazil": 5.0
      },
      "gfaPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "footprintPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 120.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Wastewater treatment facility",
      "code": "Wastewater treatment facility",
      "units": {
        "Netherlands": 1,
        "Vietnam": 1.0,
        "Brazil": 1.0
      },
      "gfaPerUnit": {
        "Netherlands": 524.1090147,
        "Vietnam": 524.1090147,
        "Brazil": 524.1090147
      },
      "footprintPerUnit": {
        "Netherlands": 524.1090147,
        "Vietnam": 524.1090147,
        "Brazil": 524.1090147
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 120.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Potable water treatment facilities",
      "code": "Potable water treatment facilities",
      "units": {
        "Netherlands": 0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gfaPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "footprintPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 120.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Services",
      "name": "Data Center",
      "code": "20cm2 pp",
      "units": {
        "Netherlands": 1.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gfaPerUnit": {
        "Netherlands": 100,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "footprintPerUnit": {
        "Netherlands": 100,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 10763.91,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": null,
        "Brazil": null
      },
      "minPopulation": null
    },
    {
      "category": "Emergency Services",
      "name": "Clinic",
      "code": null,
      "units": {
        "Netherlands": 25,
        "Vietnam": 3.0,
        "Brazil": 25
      },
      "gfaPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 500.0,
        "Brazil": 300.0
      },
      "footprintPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 2000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1500.0
    },
    {
      "category": "Emergency Services",
      "name": "Pharmacy",
      "code": null,
      "units": {
        "Netherlands": 25,
        "Vietnam": 25,
        "Brazil": 25
      },
      "gfaPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "footprintPerUnit": {
        "Netherlands": 300.0,
        "Vietnam": 300.0,
        "Brazil": 300.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1250.0
    },
    {
      "category": "Emergency Services",
      "name": "Firebrigade",
      "code": null,
      "units": {
        "Netherlands": 5,
        "Vietnam": 5,
        "Brazil": 5
      },
      "gfaPerUnit": {
        "Netherlands": 500.0,
        "Vietnam": 500.0,
        "Brazil": 500.0
      },
      "footprintPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 1000.0
    },
    {
      "category": "Emergency Services",
      "name": "Police",
      "code": null,
      "units": {
        "Netherlands": 5,
        "Vietnam": 5,
        "Brazil": 5
      },
      "gfaPerUnit": {
        "Netherlands": 500.0,
        "Vietnam": 500.0,
        "Brazil": 500.0
      },
      "footprintPerUnit": {
        "Netherlands": 250.0,
        "Vietnam": 250.0,
        "Brazil": 250.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1200.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 3000.0
    },
    {
      "category": "Industry",
      "name": "Woodworking",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": null,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Industry",
      "name": "Steel",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Industry",
      "name": "Textiles & Ceramics",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Industry",
      "name": "Electronics",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Industry",
      "name": "Constr. mats",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Industry",
      "name": "Food processing",
      "code": null,
      "units": {
        "Netherlands": 10,
        "Vietnam": 10,
        "Brazil": 10
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 2000.0
    },
    {
      "category": "Industry",
      "name": "Repair",
      "code": null,
      "units": {
        "Netherlands": 17,
        "Vietnam": 17,
        "Brazil": 17
      },
      "gfaPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "footprintPerUnit": {
        "Netherlands": 1000.0,
        "Vietnam": 1000.0,
        "Brazil": 1000.0
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 800.0
    },
    {
      "category": "Industry",
      "name": "Warehouses",
      "code": null,
      "units": {
        "Netherlands": 7,
        "Vietnam": 35,
        "Brazil": 35
      },
      "gfaPerUnit": {
        "Netherlands": 50000.0,
        "Vietnam": 10000.0,
        "Brazil": 10000.0
      },
      "footprintPerUnit": {
        "Netherlands": 50000,
        "Vietnam": 10000,
        "Brazil": 10000
      },
      "gardenPerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "terracePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "storagePerUnit": {
        "Netherlands": 0.0,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "constructionCostPerM2": {
        "Netherlands": 1000.0,
        "Vietnam": null,
        "Brazil": 0.0
      },
      "salesRevenuePerM2": {
        "Netherlands": null,
        "Vietnam": 0.0,
        "Brazil": 0.0
      },
      "minPopulation": 4000.0
    }
  ],
  "countryStats": {
    "householdSize": {
      "Netherlands": 2.1,
      "Vietnam": 3.2,
      "Brazil": 3.0
    },
    "workingPopShare": {
      "Netherlands": 0.6664837098395348,
      "Vietnam": 0.6923,
      "Brazil": 0.6664837098395348
    },
    "effectiveFtePerPerson": {
      "Netherlands": 0.88,
      "Vietnam": 0.5,
      "Brazil": 0.88
    },
    "officeM2PerInhabitant": {
      "Netherlands": 2.75,
      "Vietnam": 2.75,
      "Brazil": 2.75
    },
    "retailM2PerInhabitant": {
      "Netherlands": 1.6,
      "Vietnam": 1.6,
      "Brazil": 1.6
    },
    "infraMetersPerInhabitant": {
      "Netherlands": 11,
      "Vietnam": 11,
      "Brazil": 11
    },
    "parkingSpacePerUnit": {
      "Netherlands": 1.0,
      "Vietnam": 1,
      "Brazil": 1.0
    },
    "parksFracOfFootprint": {
      "Netherlands": 0.05,
      "Vietnam": 0.05,
      "Brazil": 0.05
    },
    "playgroundsFracOfFootprint": {
      "Netherlands": 0.02,
      "Vietnam": 0.02,
      "Brazil": 0.02
    },
    "squaresFracOfFootprint": {
      "Netherlands": 0.02,
      "Vietnam": 0.02,
      "Brazil": 0.02
    },
    "precipitationMmPerYr": {
      "Netherlands": 900.0,
      "Vietnam": 1500.0,
      "Brazil": 1400.0
    }
  },
  "openSpace": {
    "natureRatio": 0.15,
    "waterRatio": 0.07,
    "agricultureHaNlBaseline": {
      "openField": 490.4577,
      "orchard": 230.1075,
      "greenhouse": 0.0,
      "husbandry": 490.4577
    },
    "agricultureHaPerCapita": 0.024220458
  },
  "energy": {
    "pvYieldKwhPerKwp": {
      "Netherlands": 934.47,
      "Vietnam": 1489,
      "Brazil": 1349
    },
    "pvEfficiency": 0.8,
    "turbineCapacityMw": 0.1,
    "turbineYieldMwh": {
      "Netherlands": 264,
      "Vietnam": 346,
      "Brazil": 176
    },
    "biomassMwhBaseline": 1665,
    "electricityKwhPerCapita": 6202.58,
    "heatToElectricityRatio": 0.52259,
    "transportKwhPerCapita": 8156.34,
    "roofAreaPerDwellingM2": 115.0,
    "m2PerPanel": 1.6,
    "kwpPerPanel": 0.4,
    "groundPvM2PerKwp": 8.0,
    "windFootprintM2PerTurbine": 2500.0,
    "batteryStorageDaysOfDemand": 0.5
  }
};
